image: Visual Studio 2017

build_script:
- mkdir release
- cd release
- ps: .\..\release-script\releasewin64.ps1
- 7z a QUsb2Snes-all-%APPVEYOR_REPO_TAG_NAME%.7z QUsb2Snes


artifacts:
  - path: release\QUsb2Snes-all-$(APPVEYOR_REPO_TAG_NAME).7z
    name: package

deploy:
  description: "Release of $(APPVEYOR_REPO_COMMIT_TIMESTAMP)"
  provider: GitHub
  auth_token:
    secure: JF5Ki0Bz+mvMrqw5k0u7273c8GsUAqMwe/P7ts5PKLR+G7InkGqkvTqlAZb6GDGv
  artifact: release\QUsb2Snes-all-$(APPVEYOR_REPO_TAG_NAME).7z
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true

