

on:
  push:
    paths:
      - "./docs/applications/list-apps.json"
  pull_request:
    paths:
      - "./docs/applications/list-apps.json"
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./docs/applications/schema.json
          INPUT_JSONS: ./docs/applications/list-apps.json
